# Generated by Django 6.1.1 on 2026-09-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0004_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='TODO', max_length=20),
        ),
    ]
