# Generated by Django 6.1.1 on 2026-09-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0005_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='task_api.tag'),
        ),
    ]
